-- ============================================================================
-- ЗАДАНИЕ ФИНАЛ: Создать таблицу readers и промежуточную таблицу reader_books
-- ============================================================================


CREATE TABLE readers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE
);


CREATE TABLE reader_books (
    reader_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    PRIMARY KEY (reader_id, book_id),
    CONSTRAINT fk_reader FOREIGN KEY (reader_id) REFERENCES readers(id) ON DELETE CASCADE,
    CONSTRAINT fk_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);


CREATE INDEX idx_reader_books_reader ON reader_books(reader_id);
CREATE INDEX idx_reader_books_book ON reader_books(book_id);


INSERT INTO readers (name, email) VALUES
    ('Иван', 'ivan@example.com'),
    ('Мария', 'maria@example.com');

