spring.application.name=demo1
product.service.max-products=100
product.service.forbidden-names[0]=test
product.service.forbidden-names[1]=admin
product.service.allowed-categories[0]=electronics
product.service.allowed-categories[1]=books
product.service.allowed-categories[2]=clothes
product.service.allowed-categories[3]=drinks
product.service.validate-categories=true
product.service.enable-logging=true
spring.application.name=product-service
